apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard